---
version: '3.8'
services:
  service-name:
    platform: linux/x86_64. # specify the architecture here
    image: alterra-cms-iacss
  postgresql:
    image: postgres:latest
    container_name: postgresql
    ports:
      - '5432:5432'
    volumes:
      - postgre-data:/var/lib/postgresql/data
    environment:
      # Default user is -> postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: '' # Change to your unique password
    networks:
      - my-network
volumes:
  postgre-data:

networks:
  my-network:
    driver: bridge